/**
 * Karnataka Scheme Manifest
 * Comprehensive list of Karnataka state + applicable central schemes
 * Sources: govtschemes.in, sarkariyojana.com, official .gov.in sites
 *
 * NOTE: Kannada names (name_kn) need native speaker review before shipping (CLAUDE.md rule 10)
 */

export interface SchemeManifestEntry {
  slug: string;
  name_en: string;
  name_kn?: string;
  department: string;
  eligibility_summary: string;
  benefits_summary: string;
  application_url?: string;
  official_source_url?: string;
  category: string;
  tags: string[];
  target_group: string;
  benefits_type: string;
  scheme_level: "state" | "central" | "both";
  data_source: "manual" | "myscheme_hf";
}

/**
 * Karnataka state-specific schemes
 * Primary source: govtschemes.in/allschemes/Karnataka (41 listed)
 * Secondary: sarkariyojana.com/karnataka/ (70+ listed)
 */
export const KARNATAKA_STATE_SCHEMES: SchemeManifestEntry[] = [
  // === 5 GUARANTEE SCHEMES (Flagship) ===
  {
    slug: "gruha-lakshmi",
    name_en: "Gruha Lakshmi Scheme",
    name_kn: "ಗೃಹ ಲಕ್ಷ್ಮಿ ಯೋಜನೆ",
    department: "Department of Women and Child Development",
    eligibility_summary: "Women heads of households with a BPL/APL ration card in Karnataka. One woman per household. Must be the head of the family as per ration card.",
    benefits_summary: "Monthly financial assistance of Rs. 2,000 transferred directly to the woman head of household's bank account.",
    application_url: "https://sevasindhu.karnataka.gov.in",
    official_source_url: "https://dwcd.karnataka.gov.in/41/gruhalakshmi-scheme/en",
    category: "women_children",
    tags: ["women", "financial", "monthly", "bpl", "household"],
    target_group: "Women",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "yuva-nidhi",
    name_en: "Yuva Nidhi Scheme",
    name_kn: "ಯುವ ನಿಧಿ ಯೋಜನೆ",
    department: "Department of Skill Development and Livelihood",
    eligibility_summary: "Graduates and diploma holders from Karnataka who are unemployed. Must have passed degree/diploma from recognized Karnataka institution. Age limit applies.",
    benefits_summary: "Monthly unemployment allowance of Rs. 3,000 for graduates and Rs. 1,500 for diploma holders for up to 2 years while seeking employment.",
    application_url: "https://sevasindhugs.karnataka.gov.in",
    official_source_url: "https://kaushalya.karnataka.gov.in/21/yuvanidhi-scheme/en",
    category: "employment",
    tags: ["youth", "unemployment", "graduate", "diploma", "financial"],
    target_group: "Youth",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "gruha-jyothi",
    name_en: "Gruha Jyothi Scheme",
    name_kn: "ಗೃಹ ಜ್ಯೋತಿ ಯೋಜನೆ",
    department: "Energy Department",
    eligibility_summary: "Karnataka households consuming up to 200 units of electricity per month. One connection per household. Must have valid BESCOM/HESCOM/GESCOM/MESCOM/CESC connection.",
    benefits_summary: "Free electricity for domestic consumers using up to 200 units per month. The state government pays the electricity bill directly to the ESCOM.",
    application_url: "https://sevasindhu.karnataka.gov.in",
    official_source_url: "https://sevasindhu.karnataka.gov.in",
    category: "financial",
    tags: ["electricity", "free", "household", "utility"],
    target_group: "Households",
    benefits_type: "subsidy",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "anna-bhagya",
    name_en: "Anna Bhagya Scheme",
    name_kn: "ಅನ್ನ ಭಾಗ್ಯ ಯೋಜನೆ",
    department: "Department of Food and Civil Supplies",
    eligibility_summary: "BPL (Below Poverty Line) ration card holders in Karnataka. Covers Antyodaya Anna Yojana (AAY) and Priority Household (PHH) cardholders.",
    benefits_summary: "10 kg of free rice per person per month to BPL families (5 kg from central NFSA + 5 kg from state). Previously was 7 kg, enhanced to 10 kg.",
    application_url: "https://ahara.karnataka.gov.in",
    official_source_url: "https://ahara.karnataka.gov.in",
    category: "food_security",
    tags: ["food", "rice", "bpl", "ration", "free"],
    target_group: "BPL Families",
    benefits_type: "subsidy",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "shakti-free-bus",
    name_en: "Shakti Free Bus Travel Scheme",
    name_kn: "ಶಕ್ತಿ ಉಚಿತ ಬಸ್ ಪ್ರಯಾಣ ಯೋಜನೆ",
    department: "Transport Department",
    eligibility_summary: "All women in Karnataka can travel free on KSRTC, BMTC, NWKRTC, and NEKRTC government buses. Must obtain Shakti smart card.",
    benefits_summary: "Free bus travel for women on all Karnataka state government bus services. Smart card issued for identification.",
    application_url: "https://sevasindhu.karnataka.gov.in",
    official_source_url: "https://transport.karnataka.gov.in",
    category: "transport",
    tags: ["women", "transport", "free", "bus", "travel"],
    target_group: "Women",
    benefits_type: "service",
    scheme_level: "state",
    data_source: "manual",
  },

  // === WOMEN & CHILDREN SCHEMES ===
  {
    slug: "bhagyalakshmi",
    name_en: "Bhagyalakshmi Scheme",
    name_kn: "ಭಾಗ್ಯಲಕ್ಷ್ಮಿ ಯೋಜನೆ",
    department: "Department of Women and Child Development",
    eligibility_summary: "BPL families in Karnataka who give birth to a girl child. Family annual income must be below Rs. 1 lakh. Must register within one year of birth.",
    benefits_summary: "Health insurance of Rs. 25,000 for girl child. Scholarship bonds maturing at age 18 worth Rs. 34,751 to Rs. 1,00,097 depending on scheme year. Annual scholarships for education.",
    application_url: "https://dwcd.karnataka.gov.in",
    official_source_url: "https://dwcd.karnataka.gov.in",
    category: "women_children",
    tags: ["girl", "child", "bpl", "bond", "education", "insurance"],
    target_group: "Girl Children",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "thayi-bhagya",
    name_en: "Thayi Bhagya Scheme",
    name_kn: "ತಾಯಿ ಭಾಗ್ಯ ಯೋಜನೆ",
    department: "Department of Health and Family Welfare",
    eligibility_summary: "BPL pregnant women in Karnataka. Must deliver in government or empaneled private hospitals.",
    benefits_summary: "Free delivery services (normal and C-section) at government and empaneled private hospitals. Includes free medicines, diagnostics, and blood during delivery.",
    application_url: "https://healthsecretariat.karnataka.gov.in",
    official_source_url: "https://healthsecretariat.karnataka.gov.in",
    category: "health",
    tags: ["women", "pregnancy", "delivery", "health", "bpl", "free"],
    target_group: "Pregnant Women",
    benefits_type: "service",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "madilu-kit",
    name_en: "Madilu Kit Scheme",
    department: "Department of Health and Family Welfare",
    eligibility_summary: "Pregnant women delivering in government hospitals in Karnataka. Must be registered under Thayi Bhagya.",
    benefits_summary: "Free maternity kit (Madilu Kit) containing essential items for mother and newborn baby including clothes, blankets, mosquito net, soap, and other necessities.",
    application_url: "https://dwcd.karnataka.gov.in/",
    official_source_url: "https://healthsecretariat.karnataka.gov.in",
    category: "health",
    tags: ["women", "pregnancy", "maternity", "free", "kit"],
    target_group: "Pregnant Women",
    benefits_type: "service",
    scheme_level: "state",
    data_source: "manual",
  },

  // === AGRICULTURE SCHEMES ===
  {
    slug: "farm-loan-waiver",
    name_en: "Crop Loan Waiver Scheme",
    name_kn: "ಬೆಳೆ ಸಾಲ ಮನ್ನಾ ಯೋಜನೆ",
    department: "Department of Agriculture",
    eligibility_summary: "Farmers in Karnataka who have taken crop loans from cooperative banks or commercial banks. Loan amount and eligibility criteria vary by announcement year.",
    benefits_summary: "Waiver of crop loans up to Rs. 2 lakh per farmer. Covers both cooperative and commercial bank loans taken for agricultural purposes.",
    application_url: "https://raitamitra.karnataka.gov.in/",
    official_source_url: "https://raitamitra.karnataka.gov.in",
    category: "agriculture",
    tags: ["farmer", "loan", "waiver", "agriculture", "crop"],
    target_group: "Farmers",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "ganga-kalyana",
    name_en: "Ganga Kalyana Scheme",
    name_kn: "ಗಂಗಾ ಕಲ್ಯಾಣ ಯೋಜನೆ",
    department: "Social Welfare Department",
    eligibility_summary: "SC/ST farmers in Karnataka who own agricultural land. Must have minimum 1 acre of dry land or 0.5 acre of irrigated land.",
    benefits_summary: "Free borewells and pumpsets for irrigation. Government provides borewell drilling, motor and pumpset, and pipeline installation at no cost to the farmer.",
    application_url: "https://swd.karnataka.gov.in/",
    official_source_url: "https://swd.karnataka.gov.in",
    category: "agriculture",
    tags: ["sc", "st", "farmer", "irrigation", "borewell", "free"],
    target_group: "SC/ST Farmers",
    benefits_type: "service",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "krushi-aranya-protsaha",
    name_en: "Krushi Aranya Protsaha Yojane",
    department: "Department of Forest",
    eligibility_summary: "Farmers in Karnataka willing to grow tree crops on their agricultural land. Must have at least 0.5 acres of land.",
    benefits_summary: "Financial incentive for growing tree species on agricultural land. Rs. 3 per seedling per year for 3 years. Promotes agroforestry and environmental conservation.",
    application_url: "https://aranya.gov.in/",
    official_source_url: "https://aranya.gov.in",
    category: "agriculture",
    tags: ["farmer", "forestry", "agroforestry", "environment", "subsidy"],
    target_group: "Farmers",
    benefits_type: "subsidy",
    scheme_level: "state",
    data_source: "manual",
  },

  // === EDUCATION SCHEMES ===
  {
    slug: "vidyasiri",
    name_en: "Vidyasiri Scholarship Scheme",
    name_kn: "ವಿದ್ಯಾಸಿರಿ ವಿದ್ಯಾರ್ಥಿವೇತನ",
    department: "Department of Backward Classes Welfare",
    eligibility_summary: "SC/ST students in Karnataka pursuing higher education (degree, post-graduate, professional courses). Family annual income below Rs. 2.5 lakh.",
    benefits_summary: "Monthly scholarship ranging from Rs. 1,500 to Rs. 3,000 depending on the course. Covers hostel fees, maintenance, and book allowance.",
    application_url: "https://ssp.postmatric.karnataka.gov.in",
    official_source_url: "https://bcwd.karnataka.gov.in/44/vidyasiri/en",
    category: "education",
    tags: ["scholarship", "sc", "st", "education", "student", "hostel"],
    target_group: "SC/ST Students",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "arivu-education-loan",
    name_en: "Arivu Education Loan Scheme",
    name_kn: "ಅರಿವು ಶಿಕ್ಷಣ ಸಾಲ ಯೋಜನೆ",
    department: "Karnataka Minorities Development Corporation",
    eligibility_summary: "Minority community students in Karnataka pursuing professional courses (engineering, medical, MBA, etc.). Family annual income below Rs. 2.5 lakh.",
    benefits_summary: "Education loan up to Rs. 5 lakh at subsidized interest rates. Covers tuition fees, hostel expenses, and examination fees. Repayment starts after course completion.",
    application_url: "https://kmdconline.karnataka.gov.in/",
    official_source_url: "https://kmdc.karnataka.gov.in",
    category: "education",
    tags: ["minority", "education", "loan", "student", "professional"],
    target_group: "Minority Students",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "overseas-education-loan",
    name_en: "Loan Scheme for Overseas Education",
    department: "Karnataka Minorities Development Corporation",
    eligibility_summary: "Minority community students from Karnataka who have secured admission in recognized foreign universities. Family annual income below Rs. 2.5 lakh.",
    benefits_summary: "Education loan up to Rs. 20 lakh for overseas education. Covers tuition, travel, and living expenses. Subsidized interest rate with repayment after return.",
    application_url: "https://kmdconline.karnataka.gov.in/",
    official_source_url: "https://kmdc.karnataka.gov.in",
    category: "education",
    tags: ["minority", "education", "overseas", "loan", "student"],
    target_group: "Minority Students",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },

  // === SELF-EMPLOYMENT & LIVELIHOOD SCHEMES ===
  {
    slug: "udyogini",
    name_en: "Karnataka Udyogini Scheme",
    name_kn: "ಉದ್ಯೋಗಿಣಿ ಯೋಜನೆ",
    department: "Karnataka State Women's Development Corporation",
    eligibility_summary: "Women aged 18-45 in Karnataka from SC/ST/OBC/Minority communities. Family annual income below Rs. 1.5 lakh (general) or Rs. 2 lakh (SC/ST). Must have a viable business plan.",
    benefits_summary: "Loan up to Rs. 3 lakh at subsidized interest rates for starting small business or self-employment ventures. No collateral needed for loans up to Rs. 1 lakh.",
    application_url: "https://kswdc.karnataka.gov.in/21/udyogini/en",
    official_source_url: "https://kswdc.karnataka.gov.in",
    category: "employment",
    tags: ["women", "self-employment", "loan", "business", "sc", "st"],
    target_group: "Women",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "self-employment-scheme",
    name_en: "Karnataka Self Employment Scheme",
    department: "Social Welfare Department",
    eligibility_summary: "SC/ST individuals aged 18-45 in Karnataka. Family annual income below Rs. 1 lakh. Must have viable project/business proposal.",
    benefits_summary: "Loan up to Rs. 5 lakh with 50% subsidy (maximum Rs. 50,000) for starting business or self-employment. Covers activities like dairy, tailoring, auto rickshaw, etc.",
    application_url: "https://adcl.karnataka.gov.in/",
    official_source_url: "https://swd.karnataka.gov.in",
    category: "employment",
    tags: ["sc", "st", "self-employment", "loan", "subsidy", "business"],
    target_group: "SC/ST Individuals",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "shrama-shakthi-loan",
    name_en: "Shrama Shakthi Loan Scheme",
    department: "Karnataka State Women's Development Corporation",
    eligibility_summary: "Women from all communities in Karnataka aged 18-55. Family annual income below Rs. 1.5 lakh. Must have a viable business/self-employment plan.",
    benefits_summary: "Loan up to Rs. 1 lakh at 4% interest rate for income generating activities. Includes tailoring, beauty parlor, food business, and other micro-enterprises.",
    application_url: "https://kswdc.karnataka.gov.in/",
    official_source_url: "https://kswdc.karnataka.gov.in",
    category: "employment",
    tags: ["women", "loan", "self-employment", "micro-enterprise"],
    target_group: "Women",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "swavalambi-sarathi",
    name_en: "Swavalambi Sarathi Scheme",
    department: "Karnataka Backward Classes Development Corporation",
    eligibility_summary: "Members of backward classes in Karnataka aged 18-45. Family annual income below Rs. 1 lakh. Must have valid driving license.",
    benefits_summary: "Financial assistance to purchase auto-rickshaw or taxi for self-employment. Loan up to Rs. 3 lakh with subsidy component.",
    application_url: "https://dbcdc.karnataka.gov.in/",
    official_source_url: "https://dbcdc.karnataka.gov.in",
    category: "employment",
    tags: ["backward-classes", "self-employment", "auto", "taxi", "transport"],
    target_group: "Backward Classes",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "direct-loan-business",
    name_en: "Direct Loan for Business Enterprises Scheme",
    department: "Karnataka Minorities Development Corporation",
    eligibility_summary: "Minority community individuals in Karnataka with viable business proposals. Family annual income below Rs. 2 lakh.",
    benefits_summary: "Direct loan up to Rs. 10 lakh for setting up business enterprises. Subsidized interest rates with flexible repayment period.",
    application_url: "https://kmdconline.karnataka.gov.in/",
    official_source_url: "https://kmdc.karnataka.gov.in",
    category: "employment",
    tags: ["minority", "business", "loan", "enterprise"],
    target_group: "Minorities",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },

  // === SOCIAL WELFARE / MARRIAGE ASSISTANCE ===
  {
    slug: "sc-marriage-assistance",
    name_en: "SC Marriage Assistance Scheme",
    department: "Social Welfare Department",
    eligibility_summary: "Scheduled Caste families in Karnataka. Bride/groom must be SC. Family annual income below Rs. 1 lakh.",
    benefits_summary: "Financial assistance of Rs. 50,000 for marriage expenses of SC community members. Includes inter-caste and intra-caste marriages.",
    application_url: "https://swdservices.karnataka.gov.in/swincentive/ICM/ICMHome.aspx",
    official_source_url: "https://swd.karnataka.gov.in",
    category: "social_welfare",
    tags: ["sc", "marriage", "financial", "assistance"],
    target_group: "SC Families",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "santwana-scheme",
    name_en: "Santwana Scheme",
    department: "Social Welfare Department",
    eligibility_summary: "SC/ST individuals in Karnataka who are victims of atrocities. Must file complaint under SC/ST Prevention of Atrocities Act.",
    benefits_summary: "Financial compensation and rehabilitation assistance for victims of caste-based atrocities. Includes legal aid, medical treatment, and monetary relief.",
    application_url: "https://sevasindhuservices.karnataka.gov.in/",
    official_source_url: "https://swd.karnataka.gov.in",
    category: "social_welfare",
    tags: ["sc", "st", "atrocities", "compensation", "legal"],
    target_group: "SC/ST Individuals",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },

  // === HEALTH SCHEMES ===
  {
    slug: "gruha-arogya-yojana",
    name_en: "Gruha Arogya Yojana",
    department: "Department of Health and Family Welfare",
    eligibility_summary: "All households in Karnataka. Primary health care delivered at doorstep through mobile health units. Covers urban and rural areas.",
    benefits_summary: "Free doorstep primary healthcare services through mobile health teams. Includes check-ups, medicines, diagnostics, and referral services.",
    application_url: "https://arogya.karnataka.gov.in/",
    official_source_url: "https://healthsecretariat.karnataka.gov.in",
    category: "health",
    tags: ["health", "doorstep", "free", "primary-care", "rural", "urban"],
    target_group: "All Citizens",
    benefits_type: "service",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "ksrtc-arogya",
    name_en: "KSRTC Arogya Scheme",
    department: "Transport Department",
    eligibility_summary: "KSRTC employees and their dependents in Karnataka.",
    benefits_summary: "Health insurance coverage for KSRTC employees and families. Covers hospitalization, surgeries, and medical expenses at empaneled hospitals.",
    application_url: "https://ksrtc.karnataka.gov.in/",
    official_source_url: "https://ksrtc.karnataka.gov.in",
    category: "health",
    tags: ["health", "insurance", "employee", "transport"],
    target_group: "KSRTC Employees",
    benefits_type: "service",
    scheme_level: "state",
    data_source: "manual",
  },

  // === HOUSING ===
  {
    slug: "ambedkar-housing",
    name_en: "Dr. B.R. Ambedkar Housing Scheme",
    department: "Social Welfare Department",
    eligibility_summary: "SC/ST families in Karnataka who are homeless or living in kutcha houses. Family annual income below Rs. 32,000 in rural, Rs. 42,000 in urban areas.",
    benefits_summary: "Financial assistance up to Rs. 1.5 lakh for construction of pucca house. Additional funds for toilet and water connection.",
    application_url: "https://sevasindhu.karnataka.gov.in/",
    official_source_url: "https://swd.karnataka.gov.in",
    category: "housing",
    tags: ["sc", "st", "housing", "construction", "bpl"],
    target_group: "SC/ST Families",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },

  // === SKILL DEVELOPMENT ===
  {
    slug: "community-based-training",
    name_en: "Community Based Training Scheme",
    department: "Department of Skill Development",
    eligibility_summary: "Unemployed youth in Karnataka aged 18-35. Minimum 8th class education. Priority to BPL, SC/ST, women, and minorities.",
    benefits_summary: "Free skill training in 40+ trades including computer, tailoring, electrical, plumbing, beautician. Includes stipend during training period.",
    application_url: "https://kaushalya.karnataka.gov.in/",
    official_source_url: "https://kaushalkar.karnataka.gov.in",
    category: "employment",
    tags: ["skill", "training", "youth", "free", "employment"],
    target_group: "Youth",
    benefits_type: "service",
    scheme_level: "state",
    data_source: "manual",
  },

  // === SERICULTURE ===
  {
    slug: "sericulture-incentive",
    name_en: "Incentive Scheme for Sericulture Reelers",
    department: "Department of Sericulture",
    eligibility_summary: "Sericulture reelers and weavers in Karnataka who are actively involved in silk reeling. Must have a valid reeling unit.",
    benefits_summary: "Financial incentive per kg of raw silk produced. Subsidy for modern reeling equipment. Training in improved reeling techniques.",
    application_url: "https://sericulture.karnataka.gov.in/",
    official_source_url: "https://csb.gov.in",
    category: "agriculture",
    tags: ["sericulture", "silk", "reeling", "subsidy", "incentive"],
    target_group: "Sericulture Workers",
    benefits_type: "subsidy",
    scheme_level: "state",
    data_source: "manual",
  },

  // === MINORITY WELFARE ===
  {
    slug: "minority-shg-subsidy",
    name_en: "Subsidy Scheme for Self Help Groups of Minorities",
    department: "Karnataka Minorities Development Corporation",
    eligibility_summary: "Self Help Groups (SHGs) with majority minority community members in Karnataka. Group must be registered and active for at least 6 months.",
    benefits_summary: "Subsidy up to Rs. 25,000 per SHG for income generating activities. Covers group enterprises in food processing, handicrafts, tailoring, etc.",
    application_url: "https://kmdconline.karnataka.gov.in/",
    official_source_url: "https://kmdc.karnataka.gov.in",
    category: "employment",
    tags: ["minority", "shg", "subsidy", "self-help", "group"],
    target_group: "Minority SHGs",
    benefits_type: "subsidy",
    scheme_level: "state",
    data_source: "manual",
  },

  // === LEGAL / STIPEND ===
  {
    slug: "law-graduate-stipend",
    name_en: "Stipend to Law Graduates Scheme",
    department: "Social Welfare Department",
    eligibility_summary: "SC/ST law graduates in Karnataka who are undergoing apprenticeship with practicing advocates. Must be registered with Bar Council.",
    benefits_summary: "Monthly stipend during apprenticeship period to support SC/ST law graduates starting their legal practice.",
    application_url: "https://swdservices.karnataka.gov.in/swincentive/LAW/LAWHome.aspx",
    official_source_url: "https://swd.karnataka.gov.in",
    category: "education",
    tags: ["sc", "st", "law", "graduate", "stipend", "legal"],
    target_group: "SC/ST Law Graduates",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },

  // === AMBEDKAR SCHEME ===
  {
    slug: "ambedkar-karmika-sahaya",
    name_en: "Ambedkar Karmika Sahaya Hastha Scheme",
    department: "Labour Department",
    eligibility_summary: "Unorganized sector workers in Karnataka who meet BPL criteria. Must be registered with the Labour Department.",
    benefits_summary: "Financial assistance for unorganized workers including medical aid, marriage assistance, education support for children, and death benefit.",
    application_url: "https://ksuwssb.karnataka.gov.in/",
    official_source_url: "https://labour.karnataka.gov.in",
    category: "social_welfare",
    tags: ["labour", "unorganized", "bpl", "worker", "assistance"],
    target_group: "Unorganized Workers",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },

  // === ADDITIONAL POPULAR SCHEMES ===
  {
    slug: "vrutti-protsaha-loan",
    name_en: "Vrutti Protsaha Loan Scheme",
    department: "Karnataka State Women's Development Corporation",
    eligibility_summary: "Women from SC/ST/OBC communities in Karnataka aged 18-55. Family annual income below Rs. 1.5 lakh.",
    benefits_summary: "Loan up to Rs. 2 lakh at subsidized interest for women to start small businesses or livelihood activities.",
    application_url: "https://kswdc.karnataka.gov.in/",
    official_source_url: "https://kswdc.karnataka.gov.in",
    category: "employment",
    tags: ["women", "loan", "business", "livelihood"],
    target_group: "Women",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "prabhuddha-overseas-scholarship",
    name_en: "Prabhuddha Overseas Scholarship Scheme",
    department: "Social Welfare Department",
    eligibility_summary: "SC/ST students from Karnataka who have secured admission in top-ranked foreign universities. Must have excellent academic record.",
    benefits_summary: "Scholarship covering tuition fees, living expenses, airfare, and health insurance for studying abroad in top universities.",
    application_url: "https://swdservices.karnataka.gov.in/foreignstudies/",
    official_source_url: "https://swd.karnataka.gov.in",
    category: "education",
    tags: ["sc", "st", "scholarship", "overseas", "education"],
    target_group: "SC/ST Students",
    benefits_type: "financial",
    scheme_level: "state",
    data_source: "manual",
  },
  {
    slug: "free-laptop-scheme",
    name_en: "Free Laptop Distribution Scheme",
    department: "Department of Collegiate Education",
    eligibility_summary: "Government college students in Karnataka from economically weaker sections. First-year degree students with valid BPL card or income certificate.",
    benefits_summary: "Free laptop/tablet for higher education students to support digital learning. Distributed through government colleges.",
    application_url: "https://dce.karnataka.gov.in/",
    category: "education",
    tags: ["student", "laptop", "free", "education", "digital"],
    target_group: "Students",
    benefits_type: "service",
    scheme_level: "state",
    data_source: "manual",
  },
];

/**
 * Major central government schemes applicable to Karnataka residents
 * Source: myScheme.gov.in, india.gov.in
 */
export const CENTRAL_SCHEMES: SchemeManifestEntry[] = [
  {
    slug: "pm-kisan",
    name_en: "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
    department: "Ministry of Agriculture & Farmers Welfare",
    eligibility_summary: "All landholding farmer families in India with cultivable land. Excludes institutional landholders, income-tax payees, and government employees.",
    benefits_summary: "Rs. 6,000 per year in three equal installments of Rs. 2,000 directly to farmer's bank account.",
    application_url: "https://pmkisan.gov.in",
    official_source_url: "https://pmkisan.gov.in",
    category: "agriculture",
    tags: ["farmer", "financial", "agriculture", "monthly"],
    target_group: "Farmers",
    benefits_type: "financial",
    scheme_level: "central",
    data_source: "manual",
  },
  {
    slug: "pmay-urban",
    name_en: "PMAY-Urban (Pradhan Mantri Awas Yojana - Urban)",
    department: "Ministry of Housing & Urban Affairs",
    eligibility_summary: "Urban residents belonging to EWS, LIG, MIG-I, or MIG-II categories who do not own a pucca house. Annual income limits: EWS up to Rs. 3L, LIG Rs. 3-6L, MIG-I Rs. 6-12L, MIG-II Rs. 12-18L.",
    benefits_summary: "Interest subsidy on home loans (up to Rs. 2.67 lakh for EWS/LIG). Affordable housing through credit-linked subsidy scheme.",
    application_url: "https://pmaymis.gov.in",
    official_source_url: "https://pmaymis.gov.in",
    category: "housing",
    tags: ["housing", "urban", "subsidy", "loan", "ews", "lig"],
    target_group: "Urban Poor",
    benefits_type: "subsidy",
    scheme_level: "central",
    data_source: "manual",
  },
  {
    slug: "pmay-gramin",
    name_en: "PMAY-Gramin (Pradhan Mantri Awas Yojana - Gramin)",
    department: "Ministry of Rural Development",
    eligibility_summary: "Rural residents who are houseless or living in kutcha/dilapidated houses. Selected from SECC 2011 data and verified by Gram Sabha.",
    benefits_summary: "Financial assistance of Rs. 1.20 lakh (plain areas) and Rs. 1.30 lakh (hilly/difficult areas) for construction of pucca house with basic amenities.",
    application_url: "https://pmayg.gov.in",
    official_source_url: "https://pmayg.gov.in",
    category: "housing",
    tags: ["housing", "rural", "construction", "bpl"],
    target_group: "Rural Poor",
    benefits_type: "financial",
    scheme_level: "central",
    data_source: "manual",
  },
  {
    slug: "ayushman-bharat",
    name_en: "Ayushman Bharat (PM-JAY)",
    department: "Ministry of Health & Family Welfare",
    eligibility_summary: "Families identified from SECC 2011 database. Covers bottom 40% of population. No cap on family size or age. Pre-existing conditions covered from day one.",
    benefits_summary: "Health insurance cover of Rs. 5 lakh per family per year for secondary and tertiary hospitalization. Cashless treatment at empaneled hospitals across India.",
    application_url: "https://pmjay.gov.in",
    official_source_url: "https://pmjay.gov.in",
    category: "health",
    tags: ["health", "insurance", "hospitalization", "bpl", "free"],
    target_group: "BPL Families",
    benefits_type: "service",
    scheme_level: "central",
    data_source: "manual",
  },
  {
    slug: "atal-pension-yojana",
    name_en: "Atal Pension Yojana (APY)",
    department: "Ministry of Finance",
    eligibility_summary: "Indian citizens aged 18-40 with a savings bank account. Should not be income tax payer. Not a member of any statutory social security scheme.",
    benefits_summary: "Guaranteed pension of Rs. 1,000 to Rs. 5,000 per month after age 60 based on contribution amount and age of joining. Spouse continues receiving pension after death.",
    application_url: "https://www.india.gov.in/spotlight/atal-pension-yojana",
    official_source_url: "https://www.pfrda.org.in",
    category: "financial",
    tags: ["pension", "senior", "savings", "retirement"],
    target_group: "Working Adults",
    benefits_type: "financial",
    scheme_level: "central",
    data_source: "manual",
  },
  {
    slug: "pm-mudra-yojana",
    name_en: "PM MUDRA Yojana",
    department: "Ministry of Finance",
    eligibility_summary: "Any Indian citizen who has a business plan for non-farm income generating activity. Covers micro enterprises, small businesses, artisans, street vendors.",
    benefits_summary: "Collateral-free loans: Shishu (up to Rs. 50,000), Kishore (Rs. 50,000 - Rs. 5 lakh), Tarun (Rs. 5 lakh - Rs. 10 lakh). For business purposes only.",
    application_url: "https://www.mudra.org.in",
    official_source_url: "https://www.mudra.org.in",
    category: "employment",
    tags: ["business", "loan", "micro-enterprise", "self-employment"],
    target_group: "Entrepreneurs",
    benefits_type: "financial",
    scheme_level: "central",
    data_source: "manual",
  },
  {
    slug: "pmjdy",
    name_en: "PM Jan Dhan Yojana (PMJDY)",
    department: "Ministry of Finance",
    eligibility_summary: "Any Indian citizen above 10 years of age who does not have a bank account. Focus on unbanked and underbanked population.",
    benefits_summary: "Zero balance bank account with RuPay debit card, Rs. 2 lakh accident insurance, Rs. 30,000 life insurance, and overdraft facility up to Rs. 10,000.",
    application_url: "https://pmjdy.gov.in",
    official_source_url: "https://pmjdy.gov.in",
    category: "financial",
    tags: ["banking", "account", "insurance", "financial-inclusion"],
    target_group: "Unbanked Citizens",
    benefits_type: "service",
    scheme_level: "central",
    data_source: "manual",
  },
  {
    slug: "sukanya-samriddhi",
    name_en: "Sukanya Samriddhi Yojana",
    department: "Ministry of Finance",
    eligibility_summary: "Parents/guardians of girl child aged below 10 years. Maximum 2 accounts for 2 girl children (3 in case of twins).",
    benefits_summary: "High interest savings scheme (currently ~8%) for girl child education and marriage. Minimum deposit Rs. 250/year, maximum Rs. 1.5 lakh/year. Tax benefits under 80C.",
    application_url: "https://www.nsiindia.gov.in",
    official_source_url: "https://www.nsiindia.gov.in",
    category: "women_children",
    tags: ["girl", "child", "savings", "education", "marriage", "tax"],
    target_group: "Girl Children",
    benefits_type: "financial",
    scheme_level: "central",
    data_source: "manual",
  },
  {
    slug: "pm-ujjwala",
    name_en: "PM Ujjwala Yojana",
    department: "Ministry of Petroleum & Natural Gas",
    eligibility_summary: "Women from BPL households who do not have an LPG connection. Must be above 18 years. No existing LPG connection in the household.",
    benefits_summary: "Free LPG gas connection with initial refill. Financial assistance of Rs. 1,600 per connection. Subsidy on subsequent refills.",
    application_url: "https://www.pmuy.gov.in",
    official_source_url: "https://www.pmuy.gov.in",
    category: "social_welfare",
    tags: ["women", "bpl", "lpg", "gas", "cooking", "free"],
    target_group: "BPL Women",
    benefits_type: "service",
    scheme_level: "central",
    data_source: "manual",
  },
  {
    slug: "pm-kaushal-vikas",
    name_en: "PM Kaushal Vikas Yojana (PMKVY)",
    department: "Ministry of Skill Development & Entrepreneurship",
    eligibility_summary: "Indian nationals aged 15-45 who are school/college dropouts or unemployed. Priority for SC/ST, women, and persons with disabilities.",
    benefits_summary: "Free skill training in 300+ courses with industry-recognized certification. Includes placement support, stipend during training, and travel allowance.",
    application_url: "https://www.skillindiadigital.gov.in/pmkvy",
    official_source_url: "https://www.skillindiadigital.gov.in/pmkvy",
    category: "employment",
    tags: ["skill", "training", "youth", "free", "certification"],
    target_group: "Youth",
    benefits_type: "service",
    scheme_level: "central",
    data_source: "manual",
  },
  {
    slug: "nfsa-ration",
    name_en: "National Food Security Act (NFSA) Ration",
    department: "Ministry of Consumer Affairs, Food & Public Distribution",
    eligibility_summary: "Priority Households (PHH) and Antyodaya Anna Yojana (AAY) cardholders across India. Covers up to 75% rural and 50% urban population.",
    benefits_summary: "5 kg foodgrains per person per month at subsidized rates: rice Rs. 3/kg, wheat Rs. 2/kg, coarse grains Rs. 1/kg. AAY families get 35 kg/month.",
    application_url: "https://nfsa.gov.in",
    official_source_url: "https://nfsa.gov.in",
    category: "food_security",
    tags: ["food", "ration", "rice", "wheat", "bpl", "subsidized"],
    target_group: "BPL Families",
    benefits_type: "subsidy",
    scheme_level: "central",
    data_source: "manual",
  },
  {
    slug: "pm-matru-vandana",
    name_en: "PM Matru Vandana Yojana (PMMVY)",
    department: "Ministry of Women & Child Development",
    eligibility_summary: "Pregnant women and lactating mothers for first living child. Must register pregnancy at Anganwadi centre. Not applicable for miscarriage or stillbirth.",
    benefits_summary: "Cash incentive of Rs. 5,000 in three installments during pregnancy and after delivery. Promotes institutional delivery and infant immunization.",
    application_url: "https://pmmvy.wcd.gov.in",
    official_source_url: "https://pmmvy.wcd.gov.in",
    category: "women_children",
    tags: ["women", "pregnancy", "maternity", "financial", "child"],
    target_group: "Pregnant Women",
    benefits_type: "financial",
    scheme_level: "central",
    data_source: "manual",
  },
  {
    slug: "pm-svanidhi",
    name_en: "PM SVANidhi (Street Vendor Self-Reliance Fund)",
    department: "Ministry of Housing & Urban Affairs",
    eligibility_summary: "Street vendors in urban areas who have been vending before March 24, 2020. Must possess certificate of vending or letter of recommendation from ULB.",
    benefits_summary: "Working capital loan: Rs. 10,000 (1st), Rs. 20,000 (2nd), Rs. 50,000 (3rd cycle). Interest subsidy of 7%. Digital payments cashback incentive.",
    application_url: "https://pmsvanidhi.mohua.gov.in",
    official_source_url: "https://pmsvanidhi.mohua.gov.in",
    category: "employment",
    tags: ["vendor", "street", "loan", "urban", "self-employment"],
    target_group: "Street Vendors",
    benefits_type: "financial",
    scheme_level: "central",
    data_source: "manual",
  },
  {
    slug: "national-pension-scheme",
    name_en: "National Pension System (NPS)",
    department: "Ministry of Finance",
    eligibility_summary: "Indian citizens aged 18-70. NPS Lite (Swavalamban) for unorganized sector workers. Government employees auto-enrolled since 2004.",
    benefits_summary: "Market-linked pension scheme with tax benefits up to Rs. 2 lakh (80CCD). Partial withdrawal allowed. 60% lump sum + 40% annuity at retirement.",
    application_url: "https://www.pfrda.org.in",
    official_source_url: "https://www.pfrda.org.in",
    category: "financial",
    tags: ["pension", "retirement", "savings", "tax-benefit"],
    target_group: "Working Adults",
    benefits_type: "financial",
    scheme_level: "central",
    data_source: "manual",
  },
  {
    slug: "standup-india",
    name_en: "Stand Up India Scheme",
    department: "Ministry of Finance",
    eligibility_summary: "SC/ST and women entrepreneurs above 18 years. For setting up new enterprise in manufacturing, services, or trading. At least 51% shareholding by SC/ST/woman.",
    benefits_summary: "Bank loans between Rs. 10 lakh and Rs. 1 crore for greenfield enterprises. Composite loan (term + working capital). Repayment up to 7 years.",
    application_url: "https://www.standupmitra.in",
    official_source_url: "https://www.standupmitra.in",
    category: "employment",
    tags: ["sc", "st", "women", "entrepreneur", "loan", "business"],
    target_group: "SC/ST/Women Entrepreneurs",
    benefits_type: "financial",
    scheme_level: "central",
    data_source: "manual",
  },
];

/**
 * All schemes combined
 */
export const ALL_MANIFEST_SCHEMES: SchemeManifestEntry[] = [
  ...KARNATAKA_STATE_SCHEMES,
  ...CENTRAL_SCHEMES,
];
